### ISSUE TITLE
import json to maya

### ISSUE THREAD

**Issue by leety0809** [JustinPedersen/maya_fspy#5] opened 2021-04-16 13:58 UTC
i have  followed yr instructions
however 
in the maya scene it only created a cam grp and default cam with no parameter data
there are some messages form the expression editor that i don't understand
thank you
===================================================================================

# Warning: Unrecognized node type 'decomposeMatrix'; preserving node information during this session. # 
# Traceback (most recent call last):
#   File "C:/Users/user/Documents/maya/2018/scripts\maya_fspy\ui.py", line 113, in generate_camera
#     create_camera_and_plane(self.json_lineedit.text(), self.image_lineedit.text())
#   File "C:/Users/user/Documents/maya/2018/scripts\maya_fspy\core.py", line 41, in create_camera_and_plane
#     pm.connectAttr(matrix.output, decompose_matrix.inputMatrix)
#   File "C:\Program Files\Autodesk\Maya2018\Python\lib\site-packages\pymel\core\nodetypes.py", line 414, in __getattr__
#     raise AttributeError, "%r has no attribute or method named '%s'" % (self, attr)
# AttributeError: nt.Unknown(u'cameraTransform_decomposeMatrix2') has no attribute or method named 'inputMatrix'

**Comment by JustinPedersen96** [comment] 2021-04-16 14:20
Hey there. 

If possible please can you upload the .json and image file to dropbox or google drive and send me a link? 
Also what version of Maya are you currently using? 

Thanks 
- Justin

**Comment by JustinPedersen96** [comment] 2021-04-16 16:02
![Screenshot 2021-04-16 180159](https://user-images.githubusercontent.com/62013683/115052110-db59f980-9edd-11eb-8602-3d7abff23566.png)
Can you also check that this plugin is loaded in your Plugin Manager? I think this might actually be the cause of your issue @leety0809

**Comment by JustinPedersen** [comment] 2021-04-17 07:02
Im going to close the issue for now, please re-open it if you are still getting the issue after the suggested fix :)

**Closed by JustinPedersen** 2021-04-17 07:02 UTC
